export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES"
export const SHOW_COUNTRY_DETAILS = "SHOW_COUNTRY_DETAILS"
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME"
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES"

export const SUBMIT_FORM = "SUBMIT_FORM"